name: "Configure AWS Credentials"
description: "Set up a .netrc file for a set of give parameters"
inputs:
  AWS_ACCOUNT_ID:
    description: "AWS ACCOUNT ID"
    required: true

  AWS_ROLE_NAME_TO_ASSUME:
    description: ""
    required: true

  AWS_SESSION_DURATION:
    description: ""
    required: true
    default: 900

  AWS_SESSION_NAME:
    description: ""
    required: true

  AWS_REGION:
    description: "in which aws region to assume the role at ?"
    required: true
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - name: "Configure AWS credentials"
      if: ${{ inputs.AWS_ACCOUNT_ID != '' }}
      uses: aws-actions/configure-aws-credentials@v4
      env:
        AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
        AWS_ROLE_NAME_TO_ASSUME: ${{ inputs.AWS_ROLE_NAME_TO_ASSUME }}
      with:
        mask-aws-account-id: true # account id is sensitive but not secret. don't publicly expose it.
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME_TO_ASSUME }} # a role that can be assumed by GHA actions only
        role-duration-seconds: ${{ inputs.AWS_SESSION_DURATION }}
        role-session-name: ${{ inputs.AWS_SESSION_NAME }}
        aws-region: ${{ inputs.AWS_REGION }}
        unset-current-credentials: true


      
