name: "Setup .netrc"
description: "Set up a .netrc file for a set of give parameters"
inputs:
  path:
    default: "$HOME/.netrc"
    description: "Destination netrc path"
    required: true

  app_id:
    description: "ID of the GitHub App"
    required: true

  app_private_key:
    description: "Private key of the GitHub App (can be Base64 encoded)."
    required: true

outputs:
  token:
    description: "Github Token"
    value: ${{ steps.get_token.outputs.token }}


runs:
  using: "composite"
  steps:
    - uses: tibdex/github-app-token@v1
      id: get_token
      with:
        app_id: "${{ inputs.app_id }}"
        private_key: "${{ inputs.app_private_key }}"
    - name: Configure git for private modules
      run: echo "machine github.com login x-access-token password ${{ steps.get_token.outputs.token }}" > "${{ inputs.path }}"
      shell: bash
