name: Auto Assign
on:
  workflow_call:
    inputs:
      assignees:
        description: "Whom to assign the issue"
        default: "burib"
        required: true
        type: string
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ inputs.assignees }}
          numOfAssignee: 1
