name: Terraform/OpenTofu Run

on:
  workflow_call:
    inputs:
      iac_tool:
        description: "The IaC tool to use, either 'terraform' or 'opentofu'"
        default: "terraform"
        required: false
        type: string
      runs-on:
        description: "Where to run, usually ubuntu-latest or self-hosted"
        default: "ubuntu-latest"
        required: false
        type: string
      tf_version:
        description: "The version of Terraform or OpenTofu to run"
        default: "latest"
        required: false
        type: string
      tf_args:
        description: "Extra arguments to pass for plan"
        required: false
        type: string
      tf_backend_config_path:
        description: "Path to the backend config file"
        required: false
        type: string
      tf_variables_path:
        description: "Path to the variables file"
        required: false
        type: string
      tf_lock_id:
        description: "If you need to unlock the state, provide the lock id"
        required: false
        type: string
      working_directory:
        description: "Working directory containing IaC code to run"
        required: false
        default: ""
        type: string
      aws_region:
        description: "AWS Region to deploy to"
        default: "us-east-1"
        required: false
        type: string
      aws_session_duration:
        description: "For how long the AWS session is valid"
        required: false
        default: "1200" # 20 minutes
        type: string
      role_to_assume:
        description: "What AWS role to assume"
        required: false
        default: ""
        type: string
      environment: # dev, staging, prod
        description: "Environment to deploy to"
        required: true
        type: string
      tf_private_modules:
        description: "Use github app auth to allow cloning of private modules"
        default: false
        type: boolean
      tf_init_args:
        description: "Additional arguments to pass to init. Example: -reconfigure or -migrate-state"
        required: false
        type: string
        default: ""
      mask_aws_account_id:
        description: "Mask or not the aws account id"
        default: true
        type: boolean
    secrets:
      AWS_ACCOUNT_ID:
        description: "Required if role_to_assume is set"
        required: false
      GH_READ_APP_PRIVATE_KEY:
        description: "Required if tf_private_modules is set"
        required: false
      GH_READ_APP_ID:
        description: "Required if tf_private_modules is set"
        required: false

env:
  ROOT_DIR: ${{ github.workspace }}

jobs:
  terraform_plan:
    name: "${{ inputs.environment }} Plan (${{ inputs.iac_tool }})"
    runs-on: ${{ inputs.runs-on }}
    env:
      # Set the command based on the input. 'tofu' for 'opentofu', otherwise 'terraform'
      IacCommand: ${{ inputs.iac_tool == 'opentofu' && 'tofu' || 'terraform' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: "set env variables"
        id: set_env_vars
        uses: buricloud/github-workflows/.github/actions/github_tools/set_env_vars@main

      # --- Conditional Tool Setup ---
      - name: Setup Terraform
        if: inputs.iac_tool == 'terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Setup OpenTofu
        if: inputs.iac_tool == 'opentofu'
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.tf_version }}

      - name: Version check
        working-directory: ${{ inputs.working_directory }}
        id: version
        run: ${{ env.IacCommand }} --version
        continue-on-error: false

      - name: Get github read token
        if: ${{ inputs.tf_private_modules }}
        uses: buricloud/github-workflows/.github/actions/auth/netrc@main
        with:
          app_id: ${{ secrets.GH_READ_APP_ID }}
          app_private_key: ${{ secrets.GH_READ_APP_PRIVATE_KEY }}

      - name: Configure AWS credentials
        if: ${{ secrets.AWS_ACCOUNT_ID != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        with:
          mask-aws-account-id: ${{ inputs.mask_aws_account_id }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.GITHUB_ORGANISATION_NAME}}-${{ env.GITHUB_REPOSITORY_NAME}}-deployer-role
          role-duration-seconds: ${{ inputs.aws_session_duration }}
          role-session-name: "plan_${{ env.SESSION_NAME }}"
          aws-region: ${{ inputs.aws_region }}
          unset-current-credentials: true

      - name: Config plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Providers
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-${{ inputs.iac_tool }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.iac_tool }}-

      - name: Init
        working-directory: ${{ inputs.working_directory }}
        id: init
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          if [ "${{ inputs.tf_backend_config_path }}" == "" ]; then
            ${{ env.IacCommand }} init ${{ inputs.tf_init_args }} \
              -backend-config="bucket=terraform-state-bucket-${{ inputs.aws_region }}-${{ env.AWS_ACCOUNT_ID }}" \
              -backend-config="dynamodb_table=terraform-lock-table-${{ inputs.aws_region }}-${{ env.AWS_ACCOUNT_ID }}" \
              -backend-config="region=${{ inputs.aws_region }}" \
              -backend-config="key=${{ env.GITHUB_ORGANISATION_NAME}}/${{ env.GITHUB_REPOSITORY_NAME }}/${{ inputs.environment }}/${{ inputs.aws_region }}.tfstate"
          else
            ${{ env.IacCommand }} init -backend-config=${{ inputs.tf_backend_config_path }} ${{ inputs.tf_init_args }}
          fi
        continue-on-error: false

      - name: Plan
        working-directory: ${{ inputs.working_directory }}
        id: plan
        run: |
          if [ "${{ inputs.tf_lock_id }}" != "" ]; then
            # unlock if `tf_lock_id` is provided
            ${{ env.IacCommand }} force-unlock -force ${{ inputs.tf_lock_id }}
          fi

          tf_args="-input=false ${{ inputs.tf_args }}"
          if [ "${{ inputs.tf_variables_path }}" != "" ]; then
            tf_args="$tf_args -var-file=${{ inputs.tf_variables_path }}"
          else
            tf_args="$tf_args -var-file=environments/${{ inputs.environment }}.tfvars"
          fi

          mkdir -p ./terraform_plans/
          ${{ env.IacCommand }} plan $tf_args -out=./terraform_plans/terraform_plan_${{ inputs.environment }}_${{ inputs.aws_region }}.tfplan

      - name: Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        working-directory: ${{ inputs.working_directory }}
        run: |
          ${{ env.IacCommand }} apply -auto-approve ./terraform_plans/terraform_plan_${{ inputs.environment }}_${{ inputs.aws_region }}.tfplan
        continue-on-error: false
